# ////////////////////////////////////////////////////////////////////
# Deploy de api-emisor
# ////////////////////////////////////////////////////////////////////
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: Deploy en ent1-dev 1.0
  name: api-emisor-ent1-dev
  namespace: ent1-dev
  labels:
    env: dev
    emisor: ent1-dev
    componente: api-emisor
    app: api-emisor-ent1-dev
spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      componente: api-emisor
      emisor: ent1-dev
      env: dev
      app: api-emisor-ent1-dev
  template:
    metadata:
      labels:
        componente: api-emisor
        emisor: ent1-dev
        env: dev
        app: api-emisor-ent1-dev
    spec:
      terminationGracePeriodSeconds: 45
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tenant
                operator: In
                values:
                - ent
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: componente
                  operator: In
                  values:
                  - api-emisor
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: api-emisor
        image: 891899566293.dkr.ecr.us-east-2.amazonaws.com/cobre/dev/api-emisor:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 2000Mi
            cpu: '1'
          requests:
            memory: 50Mi
            cpu: '0.01'
        lifecycle:
          preStop:
            exec:
              command: 
                - sh
                - -c
                - sleep 25
        readinessProbe:
          httpGet:
            path: /api-emisor/actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api-emisor/actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /api-emisor/actuator/health
            port: 8080
          failureThreshold: 60
          periodSeconds: 10
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MULTITENANCY
          value: 'true'
        - name: TENANT_FLYWAY
          value: "false"
        - name: DB_USER_FJY03
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER_FJY03
        - name: DB_PASSWORD_FJY03
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD_FJY03
        - name: DB_USER_PXT01
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER_PXT01
        - name: DB_PASSWORD_PXT01
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD_PXT01
        - name: DB_USER_CCF56
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER_CCF56
        - name: DB_PASSWORD_CCF56
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD_CCF56
        - name: DB_USER_CCF08
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER_CCF08
        - name: DB_PASSWORD_CCF08
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD_CCF08
        - name: DB_USER_QUARTZ
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER_QUARTZ
        - name: DB_PASSWORD_QUARTZ
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD_QUARTZ
        - name: DB_USER_ZZZ99
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER_ZZZ99
        - name: DB_PASSWORD_ZZZ99
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD_ZZZ99
