#
# Servicio de core-disbursement
#
apiVersion: v1
kind: Service
metadata:
  name: core-disbursement
  namespace: cri-prod
  annotations:
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthy-threshold-count: '5'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: 200-499
    alb.ingress.kubernetes.io/tags: Environment=PROD
spec:
  type: NodePort
  selector:
    componente: core-disbursement
    disbursement: cri-prod
    env: prod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080