apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  DB_USER_FJY03: fjy03
  DB_PASSWORD_FJY03: C0br320.21*.0
  DB_USER_PXT01: pxt01
<<<<<<< HEAD
  DB_PASSWORD_PXT01: C0br320.21*.0
=======
  DB_PASSWORD_PXT01: C0br320.21*.0
  DB_USER_AAA: aaa
  DB_PASSWORD_AAA: aaa
>>>>>>> 4976a4d19c2030673a71c9aa5e36e19b40c1af45
