# ////////////////////////////////////////////////////////////////////
# Deploy de core-movil-operacion
# ////////////////////////////////////////////////////////////////////
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Deploy en ent2-prod 1.0"
  name: core-movil-operacion-ent2-prod
  namespace: ent2-prod
  labels:
    app-name: core-movil-operacion-ent2-prod
    app.kubernetes.io/instance: core-movil-operacion-ent2-prod
    env: prod
    emisor: ent2-prod
    componente: core-movil-operacion
spec:
  revisionHistoryLimit: 5
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      componente: core-movil-operacion
      emisor: ent2-prod
      env: prod
  template:
    metadata:
      labels:
        componente: core-movil-operacion
        emisor: ent2-prod
        env: prod
    spec:
      containers:
      - name: core-movil-operacion
        image: 891899566293.dkr.ecr.us-east-2.amazonaws.com/cobre/prod/core-movil-operacion
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: "2000Mi"
            cpu: "1"
          requests:
            memory: "50Mi"
            cpu: "0.01"
        env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MULTITENANCY
            value: "true"
# ///////////////////Rentelri ////////////////////////////////////////////////
          - name: DB_USER_REN73
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_REN73
          - name: DB_PASSWORD_REN73
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_REN73
# ///////////////////Torres Innovacion ////////////////////////////////////////////////
          - name: DB_USER_TOI74
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_TOI74
          - name: DB_PASSWORD_TOI74
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_TOI74
# ///////////////////Big Solutions ////////////////////////////////////////////////
          - name: DB_USER_BIG75
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_BIG75
          - name: DB_PASSWORD_BIG75
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_BIG75
# ///////////////////Servihuevo ////////////////////////////////////////////////
          - name: DB_USER_SER76
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_SER76
          - name: DB_PASSWORD_SER76
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_SER76
# ///////////////////MejiayVillegas ////////////////////////////////////////////////
          - name: DB_USER_MYV77
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_MYV77
          - name: DB_PASSWORD_MYV77
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_MYV77
# ///////////////////Equipo y Carga ////////////////////////////////////////////////
          - name: DB_USER_EYC78
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_EYC78
          - name: DB_PASSWORD_EYC78
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_EYC78
# ///////////////////Condominios Zinnia ////////////////////////////////////////////////
          - name: DB_USER_CON79
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_CON79
          - name: DB_PASSWORD_CON79
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_CON79
# ///////////////////QUARZ ////////////////////////////////////////////////
          - name: DB_USER_QUARTZ
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_QUARTZ
          - name: DB_PASSWORD_QUARTZ
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_QUARTZ

# ///////////////////Estacionamientos Lugano ////////////////////////////////////////////////
          - name: DB_USER_ELU80
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_ELU80
          - name: DB_PASSWORD_ELU80
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_ELU80
# ///////////////////Inversiones Tora ////////////////////////////////////////////////
          - name: DB_USER_ITO81
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_ITO81
          - name: DB_PASSWORD_ITO81
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_ITO81
# ///////////////////RAM ////////////////////////////////////////////////
          - name: DB_USER_RAM82
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_RAM82
          - name: DB_PASSWORD_RAM82
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_RAM82
# ///////////////////TRIARIO////////////////////////////////////////////////
          - name: DB_USER_TIO83
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_TIO83
          - name: DB_PASSWORD_TIO83
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_TIO83
# ///////////////////SACSA////////////////////////////////////////////////
          - name: DB_USER_SAC84
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_SAC84
          - name: DB_PASSWORD_SAC84
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_SAC84
# ///////////////////ALAR////////////////////////////////////////////////
          - name: DB_USER_LAR85
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_LAR85
          - name: DB_PASSWORD_LAR85
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_LAR85
# ///////////////////Tres Astronautas////////////////////////////////////////////////
          - name: DB_USER_AST86
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_AST86
          - name: DB_PASSWORD_AST86
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_AST86
# ///////////////////Mayales Plaza////////////////////////////////////////////////
          - name: DB_USER_MAY87
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_MAY87
          - name: DB_PASSWORD_MAY87
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_MAY87