# ////////////////////////////////////////////////////////////////////
# Deploy de core-transaccional
# ////////////////////////////////////////////////////////////////////
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Deploy en chu-prod 1.0"
  name: core-transaccional-chu-prod
  namespace: chu-prod
  labels:
    env: prod
    emisor: chu-prod
    componente: core-transaccional
spec:
  revisionHistoryLimit: 5
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      componente: core-transaccional
      emisor: chu-prod
      env: prod
  template:
    metadata:
      labels:
        componente: core-transaccional
        emisor: chu-prod
        env: prod
    spec:
      terminationGracePeriodSeconds: 45
      containers:
        - name: core-transaccional
          image: 891899566293.dkr.ecr.us-east-2.amazonaws.com/cobre/prod/core-transaccional
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 2000Mi
              cpu: '1'
            requests:
              memory: 50Mi
              cpu: '0.01'
          lifecycle:
            preStop:
              exec:
                command: 
                  - sh
                  - -c
                  - sleep 25
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MULTITENANCY
            value: "true"
          - name: DB_USER_FJY03
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_FJY03
          - name: DB_PASSWORD_FJY03
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_FJY03
          - name: DB_USER_PXT01
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_PXT01
          - name: DB_PASSWORD_PXT01
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_PXT01
          - name: DB_USER_CCF56
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_CCF56
          - name: DB_PASSWORD_CCF56
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_CCF56
          - name: DB_USER_CCF08
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_CCF08
          - name: DB_PASSWORD_CCF08
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_CCF08
          - name: DB_USER_CCF08
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_CCF08
          - name: DB_PASSWORD_CCF08
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_CCF08
          - name: DB_USER_CCF56
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_CCF56
          - name: DB_PASSWORD_CCF56
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_CCF56
          - name: DB_USER_CCF08
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_CCF08
          - name: DB_PASSWORD_CCF08
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_CCF08                
          - name: DB_USER_CCF32
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_CCF32
          - name: DB_PASSWORD_CCF32
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_CCF32 
################################################

          - name: DB_USER_QUARTZ
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_QUARTZ
          - name: DB_PASSWORD_QUARTZ
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_QUARTZ