# ////////////////////////////////////////////////////////////////////
# Deploy de core-client-panel
# ////////////////////////////////////////////////////////////////////
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: Deploy en ent1-prod 1.0
  name: core-client-panel-ent1-prod
  namespace: ent1-prod
  labels:
    env: prod
    emisor: ent1-prod
    componente: core-client-panel
spec:
  revisionHistoryLimit: 5
  #replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      componente: core-client-panel
      emisor: ent1-prod
      env: prod
  template:
    metadata:
      labels:
        componente: core-client-panel
        emisor: ent1-prod
        env: prod
    spec:
      terminationGracePeriodSeconds: 45
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: componente
                  operator: In
                  values:
                  - core-client-panel
              topologyKey: kubernetes.io/hostname
      containers:
      - name: core-client-panel
        image: 891899566293.dkr.ecr.us-east-2.amazonaws.com/cobre/prod/core-client-panel
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 2000Mi
            cpu: '1'
          requests:
            memory: 800Mi
            cpu: '0.01'
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 25
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MULTITENANCY
          value: 'true'
        - name: TENANT_FLYWAY
          value: 'false'
        - name: DB_USER_PXT01
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER_PXT01
        - name: DB_PASSWORD_PXT01
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD_PXT01
        - name: DB_USER_IIV214
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER_IIV214
        - name: DB_PASSWORD_IIV214
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD_IIV214
        - name: DB_USER_SON215
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER_SON215
        - name: DB_PASSWORD_SON215
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD_SON215
        - name: DB_USER_LIE216
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER_LIE216
        - name: DB_PASSWORD_LIE216
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD_LIE216
        - name: DB_USER_AAB123
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER_AAB123
        - name: DB_PASSWORD_AAB123
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD_AAB123
        - name: DB_USER_AAA111
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER_AAA111
        - name: DB_PASSWORD_AAA111
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD_AAA111
        - name: DB_USER_AAA001
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER_AAA001
        - name: DB_PASSWORD_AAA001
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD_AAA001
        - name: DB_USER_ABC002
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER_ABC002
        - name: DB_PASSWORD_ABC002
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD_ABC002
