apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: core-client-panel
  namespace: ent1-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: core-client-panel-ent1-prod
  pollingInterval: 30
  cooldownPeriod: 180
  minReplicaCount: 1
  maxReplicaCount: 10
  advanced:                                          
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 90
          policies:
          - type: Pods
            value: 1
            periodSeconds: 30
        scaleUp:
          stabilizationWindowSeconds: 180
          policies:
          - type: Pods
            value: 2
            periodSeconds: 90
          selectPolicy: Max
  triggers:
  - type: memory
    metricType: AverageValue
    metadata:
      value: "1600Mi"
  - type: cpu
    metricType: AverageValue
    metadata:
      value: "0.8"