apiVersion: v1
kind: Secret
metadata:
  name: secret-github
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Cobre-Colombia/gitops
  password: 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
  username: not-used