apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd"}}
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:dev-admin, applications, get, */*, allow
    p, role:dev-admin, applications, update, */*, allow
    p, role:dev-admin, applications, sync, */*, allow
    p, role:dev-admin, applications, override, */*, allow
    p, role:dev-admin, clusters, get, *, allow
    p, role:dev-admin, repositories, get, *, allow
    p, role:dev-admin, projects, get, *, allow
    g, pablo, role:dev-admin
    g, dev-user, role:readonly
    g, felix, role:admin