apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-group-readonly-jenkins-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-group-readonly-jenkins-clusterrole-binding
subjects:
- kind: Group
  name: eks-group-readonly-jenkins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eks-group-readonly-jenkins-clusterrole
  apiGroup: rbac.authorization.k8s.io
# ---
# #******************************** NameSpace Default ********************************
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: default
#   name: eks-group-readonly-role
# rules:
# - apiGroups:
#   - ""
#   resources: 
#   - pods
#   verbs:
#   - get
#   - list
#   - delete
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   - daemonsets
#   - statefulsets
#   - replicasets
#   verbs:
#   - get
#   - list
# - apiGroups:
#   - batch
#   resources:
#   - jobs
#   verbs:
#   - get
#   - list
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: eks-group-readonly-role-binding
#   namespace: default
# subjects:
# - kind: Group
#   name: eks-group-readonly
#   apiGroup: rbac.authorization.k8s.io
# roleRef:
#   kind: Role
#   name: eks-group-readonly-role
#   apiGroup: rbac.authorization.k8s.io
# ---
# #******************************** NameSpace CBQ-QA ********************************
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: cbq-qa
#   name: eks-group-readonly-role-qa
# rules:
# - apiGroups:
#   - ""
#   resources: 
#   - pods
#   - pods/log
#   verbs:
#   - get
#   - list
#   - delete
# - apiGroups: 
#   - ""
#   resources: 
#   - pods/exec
#   verbs: 
#   - create
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   - daemonsets
#   - statefulsets
#   - replicasets
#   verbs:
#   - get
#   - list
# - apiGroups:
#   - batch
#   resources:
#   - jobs
#   verbs:
#   - get
#   - list
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: eks-group-readonly-role-binding-qa
#   namespace: cbq-qa
# subjects:
# - kind: Group
#   name: eks-group-readonly
#   apiGroup: rbac.authorization.k8s.io
# roleRef:
#   kind: Role
#   name: eks-group-readonly-role-qa
#   apiGroup: rbac.authorization.k8s.io
# #******************************** NameSpace Util-QA ********************************
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: util-qa
#   name: eks-group-readonly-role-util-qa
# rules:
# - apiGroups:
#   - ""
#   resources: 
#   - pods
#   - pods/log
#   verbs:
#   - get
#   - list
#   - delete
# - apiGroups: 
#   - ""
#   resources: 
#   - pods/exec
#   verbs: 
#   - create
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   - daemonsets
#   - statefulsets
#   - replicasets
#   verbs:
#   - get
#   - list
# - apiGroups:
#   - batch
#   resources:
#   - jobs
#   verbs:
#   - get
#   - list
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: eks-group-readonly-role-binding-util-qa
#   namespace: util-qa
# subjects:
# - kind: Group
#   name: eks-group-readonly
#   apiGroup: rbac.authorization.k8s.io
# roleRef:
#   kind: Role
#   name: eks-group-readonly-role-util-qa
#   apiGroup: rbac.authorization.k8s.io
#   #******************************** NameSpace CVA-QA ********************************
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: cva-qa
#   name: eks-group-readonly-role-util-qa
# rules:
# - apiGroups:
#   - ""
#   resources: 
#   - pods
#   - pods/log
#   verbs:
#   - get
#   - list
#   - delete
# - apiGroups: 
#   - ""
#   resources: 
#   - pods/exec
#   verbs: 
#   - create
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   - daemonsets
#   - statefulsets
#   - replicasets
#   verbs:
#   - get
#   - list
# - apiGroups:
#   - batch
#   resources:
#   - jobs
#   verbs:
#   - get
#   - list
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: eks-group-readonly-role-binding-util-qa
#   namespace: cva-qa
# subjects:
# - kind: Group
#   name: eks-group-readonly
#   apiGroup: rbac.authorization.k8s.io
# roleRef:
#   kind: Role
#   name: eks-group-readonly-role-util-qa
#   apiGroup: rbac.authorization.k8s.io
#   #******************************** NameSpace PXT-QA ********************************
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: pxt-qa
#   name: eks-group-readonly-role-util-qa
# rules:
# - apiGroups:
#   - ""
#   resources: 
#   - pods
#   - pods/log
#   verbs:
#   - get
#   - list
#   - delete
# - apiGroups: 
#   - ""
#   resources: 
#   - pods/exec
#   verbs: 
#   - create
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   - daemonsets
#   - statefulsets
#   - replicasets
#   verbs:
#   - get
#   - list
# - apiGroups:
#   - batch
#   resources:
#   - jobs
#   verbs:
#   - get
#   - list
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: eks-group-readonly-role-binding-util-qa
#   namespace: pxt-qa
# subjects:
# - kind: Group
#   name: eks-group-readonly
#   apiGroup: rbac.authorization.k8s.io
# roleRef:
#   kind: Role
#   name: eks-group-readonly-role-util-qa
#   apiGroup: rbac.authorization.k8s.io
#   #******************************** NameSpace CST-QA ********************************
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: cst-qa
#   name: eks-group-readonly-role-util-qa
# rules:
# - apiGroups:
#   - ""
#   resources: 
#   - pods
#   - pods/log
#   verbs:
#   - get
#   - list
#   - delete
# - apiGroups: 
#   - ""
#   resources: 
#   - pods/exec
#   verbs: 
#   - create
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   - daemonsets
#   - statefulsets
#   - replicasets
#   verbs:
#   - get
#   - list
# - apiGroups:
#   - batch
#   resources:
#   - jobs
#   verbs:
#   - get
#   - list
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: eks-group-readonly-role-binding-util-qa
#   namespace: cst-qa
# subjects:
# - kind: Group
#   name: eks-group-readonly
#   apiGroup: rbac.authorization.k8s.io
# roleRef:
#   kind: Role
#   name: eks-group-readonly-role-util-qa
#   apiGroup: rbac.authorization.k8s.io
#   #******************************** NameSpace ctg-QA ********************************
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: ctg-qa
#   name: eks-group-readonly-role-util-qa
# rules:
# - apiGroups:
#   - ""
#   resources: 
#   - pods
#   - pods/log
#   verbs:
#   - get
#   - list
#   - delete
# - apiGroups: 
#   - ""
#   resources: 
#   - pods/exec
#   verbs: 
#   - create
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   - daemonsets
#   - statefulsets
#   - replicasets
#   verbs:
#   - get
#   - list
# - apiGroups:
#   - batch
#   resources:
#   - jobs
#   verbs:
#   - get
#   - list
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: eks-group-readonly-role-binding-util-qa
#   namespace: ctg-qa
# subjects:
# - kind: Group
#   name: eks-group-readonly
#   apiGroup: rbac.authorization.k8s.io
# roleRef:
#   kind: Role
#   name: eks-group-readonly-role-util-qa
#   apiGroup: rbac.authorization.k8s.io
#   #******************************** NameSpace cat-QA ********************************
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: cat-qa
#   name: eks-group-readonly-role-util-qa
# rules:
# - apiGroups:
#   - ""
#   resources: 
#   - pods
#   - pods/log
#   verbs:
#   - get
#   - list
#   - delete
# - apiGroups: 
#   - ""
#   resources: 
#   - pods/exec
#   verbs: 
#   - create
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   - daemonsets
#   - statefulsets
#   - replicasets
#   verbs:
#   - get
#   - list
# - apiGroups:
#   - batch
#   resources:
#   - jobs
#   verbs:
#   - get
#   - list
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: eks-group-readonly-role-binding-util-qa
#   namespace: cat-qa
# subjects:
# - kind: Group
#   name: eks-group-readonly
#   apiGroup: rbac.authorization.k8s.io
# roleRef:
#   kind: Role
#   name: eks-group-readonly-role-util-qa
#   apiGroup: rbac.authorization.k8s.io