apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  DB_USER_FJY03: fjy03
  DB_PASSWORD_FJY03: C0br320.21*.0
  DB_USER_PXT01: pxt01
  DB_PASSWORD_PXT01: C0br320.21*.0
  DB_USER_UTIL: util
  DB_PASSWORD_UTIL: Temporal
  # DB_PASSWORD_UTIL: C0br3Ut1l20.21 
  DB_USER_CCF08: ccf08
  DB_PASSWORD_CCF08: Cartagena2021**
  DB_USER_CCF56: ccf56
  DB_PASSWORD_CCF56: Valle2021**
  DB_USER_RYM41: rym41
  DB_PASSWORD_RYM41: Rytoymonteo2021**
  DB_USER_LUN42: lun42
  DB_PASSWORD_LUN42: luno2021**
  DB_USER_ODO50: odo50
  DB_PASSWORD_ODO50: odontoexpress2021**
  DB_USER_VER51: ver51
  DB_PASSWORD_VER51: verdi2021**
  DB_USER_FIT52: fit52
  DB_PASSWORD_FIT52: fithub2021**
  # ///////////////////quantica bpo///////////////////////////////////////////////////////
  DB_USER_QUA53: qua53
  DB_PASSWORD_QUA53: quantica2021**
  # ///////////////////La Valentina Design////////////////////////////////////////////////
  DB_USER_LVD54: lvd54
  DB_PASSWORD_LVD54: lavalentina2021**
  # ///////////////////fenalco valle////////////////////////////////////////////////
  DB_USER_FVA55: fva55
  DB_PASSWORD_FVA55: fenalcovalle2021**
  # ///////////////////soluciones BPO////////////////////////////////////////////////
  DB_USER_SOL56: sol56
  DB_PASSWORD_SOL56: soluciones2021**
  # ///////////////////Promotora Terra////////////////////////////////////////////////
  DB_USER_PTE57: pte57
  DB_PASSWORD_PTE57: promotoraterra2021**

  # ///////////////////Promotora lagos////////////////////////////////////////////////
  DB_USER_PLA59: pla59
  DB_PASSWORD_PLA59: promotoralagos2021**
  # ///////////////////Mejia y Villegas ////////////////////////////////////////////////
  DB_USER_MYV60: myv60
  DB_PASSWORD_MYV60: mejiayvillegas2021**

  # ///////////////////////////////////////////////////////////////////
  # ///////////////////////////////////////////////////////////////////
  # ///////////////////Alemana ////////////////////////////////////////////////
  DB_USER_ALA11: ala11
  DB_PASSWORD_ALA11: Temporal20.21
  # ///////////////////Andalucia ////////////////////////////////////////////////
  DB_USER_AND39: and39
  DB_PASSWORD_AND39: Temporal20.21
  # ///////////////////Barumotors ////////////////////////////////////////////////
  DB_USER_BMT02: bmt02
  DB_PASSWORD_BMT02: Temporal20.21


  # ///////////////////campesa ////////////////////////////////////////////////
  DB_USER_CAM23: cam23
  DB_PASSWORD_CAM23: Temporal20.21
  # ///////////////////Chepe y pepe ////////////////////////////////////////////////
  DB_USER_CHE27: che27
  DB_PASSWORD_CHE27: Temporal20.21

  # ///////////////////Foncomfenalco ////////////////////////////////////////////////
  DB_USER_FCF05: fcf05
  DB_PASSWORD_FCF05: Temporal20.21
  # ///////////////////quartz ////////////////////////////////////////////////
  DB_USER_QUARTZ: quartz
  DB_PASSWORD_QUARTZ: Quartz20.21*
  # ///////////////////Comfamiliar Huila////////////////////////////////////////////////
  DB_USER_CCF32: ccf32
  DB_PASSWORD_CCF32: CCF32-20.21*
  # ///////////////////Demo////////////////////////////////////////////////
  DB_USER_DEM49: dem49
  DB_PASSWORD_DEM49: DEM49-20.21*
  # ///////////////////Molino Sonora////////////////////////////////////////////////
  DB_USER_MSO64: mso64
  DB_PASSWORD_MSO64: MSO64-20.21*
  # ///////////////////Tu llanta////////////////////////////////////////////////
  DB_USER_TLL65: tll65
  DB_PASSWORD_TLL65: TLL65-20.21*
  # ///////////////////Fondefal////////////////////////////////////////////////
  DB_USER_FON66: fon66
  DB_PASSWORD_FON66: FON66-20.21*
  # ///////////////////Sanchez Polo////////////////////////////////////////////////
  DB_USER_SAP67: sap67
  DB_PASSWORD_SAP67: SAP67-20.21*
  # /////////////////// Comfenalco Boyaca ////////////////////////////////////////////////
  DB_USER_CCF10: ccf10
  DB_PASSWORD_CCF10: C0mf320.20*
  # /////////////////// Comfenalco Risaralda ////////////////////////////////////////////////
  DB_USER_CCF44: ccf44
  DB_PASSWORD_CCF44: C0mf320.21*
  #////////////////////////////////////////////////
  # /////////////////// 2da Migracion ENT /////////
  #////////////////////////////////////////////////
  # /////////////////// Solmex ////////////////////////////////////////////////
  DB_USER_SMX04: smx04
  DB_PASSWORD_SMX04: smx20.21**
  # /////////////////// Gematour ////////////////////////////////////////////////
  DB_USER_GMT06: gmt06
  DB_PASSWORD_GMT06: gmt20.21**
  # /////////////////// Juanautos ////////////////////////////////////////////////
  DB_USER_JAS08: jas08
  DB_PASSWORD_JAS08: jas20.21**
  # /////////////////// Mensajeros Urbanos ////////////////////////////////////////////////
  DB_USER_MUR09: mur09
  DB_PASSWORD_MUR09: mur20.21**
  # /////////////////// Kipi ////////////////////////////////////////////////
  DB_USER_KIP10: kip10
  DB_PASSWORD_KIP10: kip20.21**
  # /////////////////// Frubana ////////////////////////////////////////////////
  DB_USER_FRU21: fru21
  DB_PASSWORD_FRU21: fru20.21**
  # /////////////////// Time Jobs ////////////////////////////////////////////////
  DB_USER_TIM22: tim22
  DB_PASSWORD_TIM22: tim20.21**
  # /////////////////// The Pub ////////////////////////////////////////////////
  DB_USER_PUB24: pub24
  DB_PASSWORD_PUB24: pub20.21**
  # /////////////////// Megatiendas ////////////////////////////////////////////////
  DB_USER_MGT25: mgt25
  DB_PASSWORD_MGT25: mgt20.21**
  # /////////////////// Sacsa ////////////////////////////////////////////////
  DB_USER_SAC28: sac28
  DB_PASSWORD_SAC28: sac20.21**
  # /////////////////// Jokr ////////////////////////////////////////////////
  DB_USER_JOK29: jok29
  DB_PASSWORD_JOK29: jok20.21**
  # /////////////////// Trip ////////////////////////////////////////////////
  DB_USER_TRI30: tri30
  DB_PASSWORD_TRI30: tri20.21**
  # /////////////////// Geiico ////////////////////////////////////////////////
  DB_USER_GEI31: gei31
  DB_PASSWORD_GEI31: gei20.21**
  # /////////////////// La Cruda ////////////////////////////////////////////////
  DB_USER_CRU35: cru35
  DB_PASSWORD_CRU35: cru20.21**

  # /////////////////// Fujiyama santa marta ////////////////////////////////////////////////
  DB_USER_FJS38: fjs38
  DB_PASSWORD_FJS38: fjs20.21**
  # /////////////////// Yokomotor ////////////////////////////////////////////////
  DB_USER_YKM40: ykm40
  DB_PASSWORD_YKM40: ykm20.21**
  # /////////////////// Incoarroz ////////////////////////////////////////////////
  DB_USER_ICA45: ica45
  DB_PASSWORD_ICA45: ica20.21**
  # /////////////////// SMS Electronic ////////////////////////////////////////////////
  DB_USER_SMS46: sms46
  DB_PASSWORD_SMS46: sms20.21**
  # /////////////////// Casa Britanica ////////////////////////////////////////////////
  DB_USER_CAS47: cas47
  DB_PASSWORD_CAS47: cas20.21**
  # /////////////////// Harrisa Foods ////////////////////////////////////////////////
  DB_USER_HFD48: hfd48
  DB_PASSWORD_HFD48: hfd20.21**
  #////////////////////////////////////////////////
  # /////////////////// Empresas nuevas ENT  (completamos 50 empresas en ENT1)/////////
  #////////////////////////////////////////////////

  # /////////////////// Promotora Innova Park S.A.S ////////////////////////////////////////////////
  DB_USER_PIP69: pip69
  DB_PASSWORD_PIP69: pip20.21**
  # /////////////////// Araujo y Segovia Zona Norte ////////////////////////////////////////////////
  DB_USER_ASN70: asn70
  DB_PASSWORD_ASN70: asn20.21**
  # /////////////////// Araujo y Segovia cordoba ////////////////////////////////////////////////
  DB_USER_ASC71: asc71
  DB_PASSWORD_ASC71: asc20.21**
  # /////////////////// OperadoraH2R ////////////////////////////////////////////////
  DB_USER_OPE72: ope72
  DB_PASSWORD_OPE72: ope20.21**

######################### REDTECHNOLOGY SAS ########################################################

  DB_USER_RAD103: rad103
  DB_PASSWORD_RAD103: C0br3.rad

######################### REDTECHNOLOGY SAS ########################################################

  DB_USER_DIS104: dis104
  DB_PASSWORD_DIS104: C0br3.dis
  ######################### Inversiones Escaf Haddad ########################################################

  DB_USER_IHE105: ihe105
  DB_PASSWORD_IHE105: C0br3.ihe
  ######################### THE PUB S A S ########################################################
  DB_USER_THB106: thb106
  DB_PASSWORD_THB106: C0br3.thb
######################### Ninania S.A.S ########################################################
  DB_USER_NAA107: naa107
  DB_PASSWORD_NAA107: C0br3.naa
  ######################### CLASSIC JEANS SHOPS S.A.S. ########################################################
  DB_USER_CSA108: csa108
  DB_PASSWORD_CSA108: C0br3.csa
  ######################### SALES INMOBILIARIA S.A ########################################################
  DB_USER_SAL109: sal109
  DB_PASSWORD_SAL109: C0br3.sal
   ######################### Proyectos Montajes y Construcciones SA Promocon ########################################################
  DB_USER_POO110: poo110
  DB_PASSWORD_POO110: C0br3.poo


  DB_USER_ASE145: ase145 # ///// A TIEMPO S. A. S /////
  DB_PASSWORD_ASE145: C0br3.ase145
  DB_USER_DAC146: dac146  # ///// DATA TECHNOLOGY S.A.S /////
  DB_PASSWORD_DAC146: C0br3.dac146
  DB_USER_APA147: apa147  # ///// A TIEMPO S. A. S /////
  DB_PASSWORD_APA147: C0br3.apa147
  DB_USER_DST148: dst148  # ///// DATA TECHNOLOGY S.A.S /////
  DB_PASSWORD_DST148: C0br3.dst148
  DB_USER_AEM149: aem149  # ///// A TIEMPO S. A. S /////
  DB_PASSWORD_AEM149: C0br3.aem149
  DB_USER_DOA150: doa150  # ///// DATA TECHNOLOGY S.A.S /////
  DB_PASSWORD_DOA150: C0br3.doa150
  DB_USER_AOP151: aop151  # ///// A TIEMPO S. A. S /////
  DB_PASSWORD_AOP151: C0br3.aop151
