# ////////////////////////////////////////////////////////////////////
# Deploy de core-movil-operacion
# ////////////////////////////////////////////////////////////////////
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Deploy en pxt-prod 1.0"
  name: core-movil-operacion-pxt-prod
  namespace: pxt-prod
  labels:
    app-name: core-movil-operacion-pxt-prod
    app.kubernetes.io/instance: core-movil-operacion-pxt-prod
    env: prod
    emisor: pxt-prod
    componente: core-movil-operacion
spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      componente: core-movil-operacion
      emisor: pxt-prod
      env: prod
  template:
    metadata:
      labels:
        componente: core-movil-operacion
        emisor: pxt-prod
        env: prod
    spec:
      containers:
      - name: core-movil-operacion
        image: 891899566293.dkr.ecr.us-east-2.amazonaws.com/cobre/prod/core-movil-operacion
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: "2000Mi"
            cpu: "1"
          requests:
            memory: "50Mi"
            cpu: "0.01"
        env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MULTITENANCY
            value: "false"
          - name: DB_USER_PXT01
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER_PXT01
          - name: DB_PASSWORD_PXT01
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD_PXT01